services:
  - type: web
    name: collab-editor-socket
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm run start:socket
    envVars:
      - key: NODE_ENV
        value: production
      - key: SOCKET_PORT
        value: 10000
      - key: NEXT_PUBLIC_APP_URL
        sync: false
